# Generated by Django 4.1.4 on 2023-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_alter_resumedata_address_alter_resumedata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
