# Generated by Django 4.1.4 on 2023-03-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_resumedata_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedata',
            name='experience',
        ),
    ]
