# Generated by Django 4.1.4 on 2023-03-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0006_resumedata_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='declaration',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
